sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
    - "node_modules"

after_success:
  - docker build -t mike1pol/itgm-bot .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push mike1pol/itgm-bot;
    fi
